#%RAML 1.0 DataType
type: object

properties:

  message:
    type: string
  bookingId:
    type: number  
  passengerNames:
    type: array
  departureDate:
    type: date-only
  departureTime:
    type: time-only
